### ISSUE TITLE
OMEMO encryption issue with pictures/videos on Monal end

### ISSUE THREAD

**Issue by zerobytes999** [anurodhp/Monal#418] opened 2020-07-18 13:58 UTC
Dear sir,
so this issue is between Conversations <-----> Monal
So I did a test, compiled Monal and used it on a Virtual device. I noticed that on Monal only the encrypted images with OMEMO are not being displayed correctly, where sent and received encrypted pictures using OMEMO dispalyed correctly in conversations. 

Below picture shows the image that was received from conversations and sent to conversations. I confirmed this on the latest update on iOS (app from the store on a friends phone). I also noticed the same thing with videos sent and received producing the same bug.

I thank you very much for the effort in creating such an amazing application,
![omemoIOS](https://user-images.githubusercontent.com/61564840/87853998-93428200-c91f-11ea-9966-c6c38c806820.PNG)

**Comment by Echolon** [comment] 2020-07-18 15:31
Hi @zerobytes999,

thank you for your report, but I think this is a duplicate of

**Allow downloading aesgcm (non image) URLs** #256

Therefore I am going to close this. The issue is known to the developers.

**Closed by Echolon** 2020-07-18 15:31 UTC
Labels: :fish: OMEMO, :iphone: iOS, :no_entry_sign:  Bug / Stability
