### ISSUE TITLE
Build 407 sends chat messages to myself

### ISSUE THREAD

**Issue by schwindp** [anurodhp/Monal#279] opened 2019-09-05 08:16 UTC
Setup:
I'm connected to my XMPP server using two clients, Monal and mcabber. When chatting with someone else (from mcabber), for every message sent to a 3rd party, I get a notification on my Monal lock screen (iOS 13.1b) as if I sent these to myself. That's not how carbons behaved until v405.

mcabber version used: 1.1.0-1-1

**Comment by ge0rg** [comment] 2019-09-05 08:27
This looks like Monal is showing a notification when it receives a "sent" carbon from another device.

Tapping that notification will open a chat with yourself, that wil contain a selection of old Carbons.

**Comment by mbirth** [comment] 2019-09-11 17:34
Same here with Monal 3.8.3 (407) and Gajim. When I reply to messages from Gajim, I get a notification on my iPhone. Also, the notification count increases and doesn't always reset if you open Monal and go to the chat normally. Only the other party's unread messages are subtracted from the count. Sometimes it resets correctly, though.

**Comment by mbirth** [comment] 2019-09-15 13:55
Replies from myself sent from a different client still show a (separate) notification on my iPhone and increase the notification count.

Ideally, it should mark all previous messages from that conversation as "read" and remove any notifications from the lock screen (and decrease the counter).

**Comment by anurodhp** [comment] 2019-09-15 14:11
I’ve reopened. Is this still on the latest beta?

**Comment by anurodhp** [comment] 2019-09-15 14:14
To clarify is there is notification or is the issue the cpu t going up?

**Comment by mbirth** [comment] 2019-09-15 14:48
Version is 3.8.3 (415). I think the issue is that messages from myself are handled like they're from someone else, i.e. they show up as a notification on the lock screen and the count increases.

**Comment by ge0rg** [comment] 2019-09-17 12:08
No more self-message notifications in build 423.

However, please-pretty-please remove the notification for a given JID if you see a "sent" carbon with an active chat state or with a body to that JID.

**Comment by anurodhp** [comment] 2019-09-17 12:22
Can you clarify what you mean this.

**Comment by ge0rg** [comment] 2019-09-17 13:20
When Monal receives a "sent" Carbon, this is most probably a sign of my activity from one of my other devices:

* if the Carbon contains an ["active" chat state](https://xmpp.org/extensions/xep-0085.html#table-1), or a ["displayed" / "acknowledged" Marker](https://xmpp.org/extensions/xep-0333.html#format), directed at a certain JID, then I've most probably just seen/read the incoming messages from that JID.
* if the Carbon contains a "sent" `<body/>` element, then I just responded to the JID.

Those are signs that I already know about the conversation with JID, so Monal should hide the notification(s) of the conversation with JID.

**Comment by mbirth** [comment] 2019-09-17 16:51
I think this should go to a separate issue as the actual problem described by OP seems fixed now.

**Comment by anurodhp** [comment] 2019-12-13 04:29
I think this is resolved.

**Closed by anurodhp** 2019-12-13 04:29 UTC
