### ISSUE TITLE
[iOS] PUSH (new information: "5 minute barrier")

### ISSUE THREAD

**Issue by FRNK-BK** [anurodhp/Monal#212] opened 2019-02-17 10:38 UTC
Hi Anu, I know we already talked about it, and it drives me crazy (that my iPhone pals don't get my messages). So I got me an iPhone (4S) JUST to hunt down this bug!!!

I can reproduce this EVERY time:
- Start Monal
- Close Monal (really close the App, let iPhone go to sleep.)
- Wait 5 Minutes! (IMPORTANT: 4 Minutes is NOT ENOUGH!!! I tried this hellalot of times!)
- Send message to account Monal is logged in to (from another device/client*).

Expected Result: Notification sound and message.
Actual Result: NO Notification on iPhone at ALL!

Two side facts:
- the sender does NOT get a "message received" (double check mark)
- the message is NOT saved as an "offline message" on eJabberd server (so I suspect, Monal already has it)

(When Monal afterwards is then started manually, _sometimes_ the message is received**, with timestamp of 'now'. Sender still does NOT get 'received' notification. But anyway _sometimes_ the message is totally lost, especially with follow ups.)

** it seems starting the the app again and wait, does not help. I have to _select_ the corresponding 'chat' and _then_ the message appears (without notification though).

*as a client I used: 
1) telepathy (Sailfish OS)
2) Smoose (Sailfish OS)
3) Dino (Linux)
ALL THE SAME RESULT.

So PLEASE confirm that you can reproduce this (5 MINUTES!!!!) so that we all can hope this issue gets addressed. (As for me, it renders the app unusable, unfortunately, because everything else is really, really good about Monal)

And: Yes, I used the current "Testflight" version of Monal (Version 3.5 (337), so your answer to issue #200 does not solve this.

I really hope we get this fixed. Thanks for everything Anu!
Cheers, 
Frank

**Comment by anurodhp** [comment] 2019-02-17 12:10
May people have been looking at this. It appears that the issue is related (or caused by) to an error when ejabberd communicates with the prosody server that I use for push.  We are trying to fix it. You can see the progress here on the prosody module 
https://github.com/tmolitor-stud-tu/mod_push_appserver/issues/15

**Comment by FRNK-BK** [comment] 2019-02-17 12:15
So I guess this was a confirmation of the issue?
You/anyone can reproduce this (also using a eJabbed server)?

Good to see that this is addressed.

**Comment by anurodhp** [comment] 2019-02-17 12:16
yes I am working with the developers

**Comment by anurodhp** [comment] 2019-02-26 04:12
server has been updated. Let me know if you still have problems (https://monal.im/blog/resolving-push-with-ejabberd/)

**Closed** 2019-02-26 04:13 UTC

**Comment by FRNK-BK** [comment] 2019-02-26 06:33
Great. This is a BIG improvement. I just did some tests and I was able to get Monal to wake up from _eternal sleep_ and to display a notification!! Thank you!!!

However, I had two send TWO messages. The first message was ignored and lost.
I'll do some testing to make sure, but unfortunately it looks reproducible...

**Comment by FRNK-BK** [comment] 2019-02-26 08:25
I am having a hard time telling, when a message is received, when it triggers notification, etc... Adding group chat to the equation complicates everything... like multiple messages, asynchronous timestamps... **I will stop testing for now.**

When I have time again, I will try to do more testing and eliminating distracting factors like other clients, other servers, broken MUC subscriptions or whatever... I think for testing one needs a clean environment. Otherwise it's just confusing.

**Comment by WainPetopia** [comment] 2019-03-17 04:53
I'm afraid this improved nothing for me. I still don't see any messages arrive unless I happen to have the app foregrounded at the time. Recently I found out that some messages being sent to me weren't arriving at all, though I can't prove that was the app and not a server issue.
