### ISSUE TITLE
[Feature request] Allow resizing of the window and left pane

### ISSUE THREAD

**Issue by bouscram** [anurodhp/Monal#125] opened 2018-11-01 14:53 UTC
Hi. I like the streamlined look of Monal on Mac, but I really would like to resize down the width of the window and left pane (or even be able to hide it temporarily - as I have only one active contact I use Jabber with).
Thanks

**Comment by anurodhp** [comment] 2018-12-07 03:05
dupe of 
https://github.com/anurodhp/Monal/issues/92

**Closed by anurodhp** 2018-12-07 03:05 UTC
