### ISSUE TITLE
Delete Prior Conversations with Contact

### ISSUE THREAD

**Issue by mayjethva** [anurodhp/Monal#241] opened 2019-05-04 17:29 UTC
I would like to know how to delete old messages with contacts.  I have gone through and swiped them out to delete, have closed the conversation and have deleted the contact and re-added.  None of these work and the messages reappear once I start a new chat.

Is there a special way to do this or is it currently being worked on?

Thanks.

**Comment by Echolon** [comment] 2019-05-05 11:07
Ref.

**Option request: Delete full history per contact at once** #180

**Comment by Echolon** [comment] 2020-01-04 22:08
@mayjethva I will close this as this is a duplicate of #180 I think.

Please report if you see anything different!

**Closed by Echolon** 2020-01-04 22:08 UTC
Labels: Feature
