### ISSUE TITLE
RFCs and XEPs support page with version

### ISSUE THREAD

**Issue by Neustradamus** [anurodhp/Monal#96] opened 2018-03-15 22:13 UTC
It is possible to have a XEPs and RFCs support page with version (XEP-XXXX v1.2)?

Examples:
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by Echolon** [comment] 2020-01-04 16:38
@Neustradamus 

Is your issue an duplicate of this actually? 

**What are the supported XEPs?** #54

**Comment by Neustradamus** [comment] 2020-01-04 17:48
@Echolon: I request a document here which will be updated all time :)
The previous ticket, is only a question ah ah

**Comment by Echolon** [comment] 2020-01-04 21:28
Is that pull request what you expect?

**Comment by Neustradamus** [comment] 2020-01-04 21:45
A document with all feature details:
- all XEPs with VERSION (XEP-XXXX v1.2)
- all RFCs

**Comment by Echolon** [comment] 2020-04-04 14:10
@Neustradamus 

Today I created a XEP file, which will be filled with information by time. Help is highly appreciated!

https://github.com/anurodhp/Monal/blob/develop/XEPsupport.md

Thanks to @marmistrz

**Closed by Echolon** 2020-04-04 14:10 UTC
Labels: XEP

**Comment by Neustradamus** [comment] 2020-04-04 18:00
@Echolon, @marmistrz, A very good start, thanks!

You have forgotten RFCs, can you add RFCs too?
