### ISSUE TITLE
Message timezone mismatch

### ISSUE THREAD

**Issue by marmistrz** [anurodhp/Monal#313] opened 2019-12-22 12:42 UTC
Messages are apparently using UTC for outgoing messages but localtime for incoming messages. See the attached image:

![monal2](https://user-images.githubusercontent.com/2914938/71321875-5ebd3380-24c0-11ea-8388-8551f2e071dd.jpg)

The blue message was actually sent by the Monal user at 21:24 CET, but is displayed as 20:24. The incoming messages (sent by me) are off by 4 minutes, e.g. the 20:49 message was actually sent at 20:53 CET.

As a result, the messages in the chat are displayed out of order. 

Both accounts are on the same server: wiuwiu.de. I'm using Conversations/gajim, the other party is using Monal. 

cc @sebastiansterk (the server admin)

/edit: XEP-0203 says that the timestamps for delayed delivery are UTC timestamps. I suppose that Monal doesn't convert this timestamp to localtime and that this is the cause of the bug.

**Comment by chippisc** [comment] 2019-12-24 11:37
We are experiencing similar problems.
Both XMPP-Accounts are on wiuwiu.de. One client is Conversations, the other one Monal.

The first screenshot shows the display of newly received messages while the user has Monal opened and views the current chat.
![before-reload](https://user-images.githubusercontent.com/56129198/71410803-019fba00-2647-11ea-82b8-bfafaafe0a41.PNG)

The second screenshot shows the display of messages that have been received while Monal was not opened. The same thing happens after closing and opening Monal again. This behaviour also applies when any other chat or the contact list is viewed while messages are received.
![after-reload](https://user-images.githubusercontent.com/56129198/71410811-08c6c800-2647-11ea-93fb-3f43c88c6320.PNG)

Outgoing messages are at first displayed correctly but after reopening the chat the time is displayed wrong. So basically there is the same problem as for incoming messages.

Before the most recent update (4.2) we also had problems with messages being displayed in wrong order. However after the update it does mostly not change the order. We had messages displayed in wrong order after the update but are not able to reproduce this issue.

Maybe @sebastiansterk can help if you need information about the server time.

**Comment by Echolon** [comment] 2019-12-24 11:51
May you also confirm via other servers eventually?

24 dic. 2019 12:37:23 PM chippisc <notifications@github.com>:

**Comment by chippisc** [comment] 2019-12-24 11:58
We now also tested with both accounts on jabber.ccc.de and experienced the exact same issue.
> May you also confirm via other servers eventually? 24 dic. 2019 12:37:23 PM chippisc <notifications@github.com>:
> […](#)

**Comment by marmistrz** [comment] 2019-12-24 12:10
I asked Sebastian about the server timezone and it's current German time, i.e. CET.

**Comment by anurodhp** [comment] 2020-01-01 17:41
I can verify this is an issue. fixing.

**Comment by anurodhp** [comment] 2020-01-01 21:41
fixed in the next beta. reopen if still an issue,

**Closed by anurodhp** 2020-01-01 21:41 UTC
