### ISSUE TITLE
[MacOS] OMEMO key not pulled from contact

### ISSUE THREAD

**Issue by ioscanner** [anurodhp/Monal#285] opened 2019-09-20 14:41 UTC
It seems the MacOS desktop version is not pulling keys from a contact.  If I click the lock and view the keys for the contact now keys are found.  It works fine on IOS and Android.  But seems the MacOS version is not working with OMEMO.

**Comment by Echolon** [comment] 2019-12-19 14:20
@ioscanner Is that still existent within the recent version?

**Comment by foss-** [comment] 2020-01-05 00:31
Confirming this bug. Reproduce steps:

* add new contact
* enable omemo
* click "i" icon > Encryption keys

No keys listed.

**Comment by anurodhp** [comment] 2020-02-20 11:47
The issue of keys not being pulled appears to be related to contacts subscription. I’ve added better info in the contacts details screen for 4.4 if contacts need to be added

**Comment by foss-** [comment] 2020-03-01 12:16
Version 4.5 (579) verified
https://github.com/anurodhp/Monal/commit/92f074153730503cfa72811e634504f61af4efc4

**Comment by licaon-kter** [comment] 2020-03-06 11:15
Version 4.5 (579)

I see "unknown subscription"...now what?

I can receive OMEMO encrypted from Conversations or from the same account connected via Converse.

But I can't send...

**Comment by foss-** [comment] 2020-03-06 12:52
Not fully fixed it seems. When I open + > View Contact Requests I see two pending requests. When I click on them they vanish. But when I re-open, the requests are there again.

For me this results in this situation:
![key fetching](https://user-images.githubusercontent.com/5708172/76085003-741b0780-5fb1-11ea-922a-63a5f4f623bc.png)
"You can see their keys. But they can't see yours."

That would make sense, as I can't seem to accept their request.

It is still odd, since despite me seeing keys for such a contact, I do not see any lock so I am unable to activate omemo on my side.

**Comment by Echolon** [comment] 2020-03-06 13:04
@anurodhp seem to be a problem still :disappointed:

**Comment by sirdrakeistda** [comment] 2020-04-11 21:47
There is the same problem on iOS (see #379). Interesting is, that the error changed after update.

**Comment by licaon-kter** [comment] 2020-07-19 19:54
Got some time with one of the two iOS users, latest _(I guess)_ 4.6 (616) iirc.

Almost all their contacts had OMEMO on and the lock icon was black, as expected.

But, one contact had no luck :) `"You can see their keys. But they can't see yours."`

Yet every message was encrypted properly, both ways.

Fun

**Comment by tmolitor-stud-tu** [comment] 2020-07-19 20:08
Something with roster subscriptions being only one way I guess.
Currently you would have to use another client to check that as far as I know.

**Comment by licaon-kter** [comment] 2020-07-19 21:58
They do have Conversations logged in on another device too, but didn't have it at hand to do any operations.
I've tried removing the iOS user from their contacts Conversations.
Toggled Presence subscriptions on/off several times from their contacts Conversations.
Logged off/on Monal several times.

But no change...

**Comment by foss-** [comment] 2020-07-20 07:41
Keep in mind this could as well be related to the byte size problem if I am not mistaken, right?
Maybe an overview over which client supports what byte size receiving / sending could be created in the wiki?

Seeing this problem on Monal with a contact using Android / Linux with various clients so a bit hard to pinpoint which client is preventing omemo as I am indeed seeing two omemo fingerprints for that contact when checking.

**Comment by licaon-kter** [comment] 2020-07-20 07:56
What byte size? IV? That should not be an issue here. Again...messages get encrypted & decrypted both ways. Just that the contact info sheet says otherwisee

**Comment by sirdrakeistda** [comment] 2020-07-20 08:33
I had this Problem only with one Monal contact. So I don't think it is a problem with special clients. Both had only one device. I don't know where the difference was. I was both times the contact with Conversations. The only difference between this scenarios was, that one device was an iPhone XS and the other one an iPhone 6. For me it seems like a random bug in Monal. For me it seems like Monal does not get the keys from the server.

**Comment by licaon-kter** [comment] 2020-07-20 08:51
Add a data point, afaik this was iOS 12 on a 6.

**Comment by FriedrichAltheide** [comment] 2020-11-02 17:58
fixed in alpha

e92e718c26a379b726872bd6b0de5d331fc158db
ba7aca4929f11e6b81ab673e1d4bd05efa0100a7

**Closed by FriedrichAltheide** 2020-11-02 17:58 UTC
Labels: :desktop_computer: Catalyst, :fire:  Priority, :fish: OMEMO, :iphone: iOS
