### ISSUE TITLE
I can't log in to a group chat

### ISSUE THREAD

**Issue by fetalon** [anurodhp/Monal#508] opened 2020-10-30 12:12 UTC
### Description of my issue or feature request:

I go to a group chat and can't write messages there! The text sends, but writes: error: modify - not-acceptable, I can't understand what the error is related to

### The Monal version and system version I use:
iOS - version 4.8(658)

### Additional information like screenshots:
![B385ABE6-B8F1-4FA3-9791-774C11A36703](https://user-images.githubusercontent.com/73699410/97703783-40519c80-1ac2-11eb-92ac-756f4b5d4bd4.jpeg)

---
[ ] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by fetalon** [comment] 2020-10-30 12:15
I go to the group through adding a group, write there, the first message comes all normanno, and the rest of the solbscheniya gives an error

**Comment by fetalon** [comment] 2020-10-30 12:19
What should I do with this problem and how can I fix it

**Comment by licaon-kter** [comment] 2020-10-30 12:44
Are you allowed to write there?

**Comment by Echolon** [comment] 2020-10-30 13:06
@fetalon thank you for reporting!

Please confirm the previoys statement.

However, group

**Comment by fetalon** [comment] 2020-10-30 15:09
Yes it is allowed to write

In the chat itself, I am approved as someone who can log in to it and after that, I can write one message, after it prohibits writing, writes an error like in the picture.

Отправлено с iPhone

**Comment by tmolitor-stud-tu** [comment] 2020-10-31 00:49
Muc is currently broken, will be fixed in monal 5.0

**Closed by tmolitor-stud-tu** 2020-10-31 00:49 UTC
Labels: :busts_in_silhouette: MUC, :desktop_computer: Catalyst, :no_entry_sign:  Bug / Stability

**Comment by Echolon** [comment] 2020-10-31 10:34
I think that is also a duplicate of #349
