### ISSUE TITLE
Handling of received pictures

### ISSUE THREAD

**Issue by thirtyfiveo** [anurodhp/Monal#213] opened 2019-02-19 20:48 UTC
Monal don't resolve the URLs like "aesgcm://xmpp-share.mailbox.org/[...]"

[Mailbox.org](https://mailbox.org/en/) ist one of the major email provider/hoster, which respect the user privacy in germany and for their XMPP server they [cooperated](https://mailbox.org/en/post/daniel-gultsch-creator-of-conversations-visits-mailbox-org-6428) with Daniel Gultsch.

**Comment by FRNK-BK** [comment] 2019-02-20 14:03
[_Conversations_](https://conversations.im/) also uses URLS like that.
"aesgcm://share.conversations.im/[...]"

**Comment by thirtyfiveo** [comment] 2019-02-20 18:42
> [_Conversations_](https://conversations.im/) also uses URLS like that.
> "aesgcm://share.conversations.im/[...]"

Do Monal display the image behind the Conversations-URL?

**Comment by thirtyfiveo** [comment] 2019-02-20 18:43
> [_Conversations_](https://conversations.im/) also uses URLS like that.
> "aesgcm://share.conversations.im/[...]"

Do Monal display the image behind the Conversations-URL?

**Comment by FRNK-BK** [comment] 2019-02-20 18:46
Unfortunately I can not tell that. The friend who has his account at conversations.im does just send me messages to my account on a non-iPhone. But the link is like that. ;)
(Yes, I could connect and try, but I suppose its all the same as with mailbox.org...)

**Comment by thirtyfiveo** [comment] 2019-02-20 21:06
Oh, it would be great, if you can reproduce my error by another server.

**Comment by thirtyfiveo** [comment] 2019-02-20 21:07
Oh, it would be great, if you can reproduce my error by another server.

**Comment by pgeorgi** [comment] 2019-03-04 11:56
Conversations seems to use that scheme by default on all http upload servers. aes-gcm indicates that it's encrypted, with the key residing in the fragment part: https://xmpp.org/extensions/inbox/omemo-media-sharing.html#aesgcm

**Comment by pgeorgi** [comment] 2019-03-04 12:00
Also note that for aes-gcm there is no separate messaging intended that it's supposed to be a shared media file instead of a pasted link, so as soon as such URIs appear, they should be considered inline media

**Comment by cweiske** [comment] 2019-03-18 15:39
I think this is a duplicate of #176.

**Comment by anurodhp** [comment] 2019-03-19 02:18
yes it is the same issue

**Closed by anurodhp** 2019-03-19 02:18 UTC
