### ISSUE TITLE
Set your own screenname for a contact

### ISSUE THREAD

**Issue by thephishermen** [anurodhp/Monal#174] opened 2019-01-09 10:04 UTC
It would be great if Monal would support the feature of maintaining your own ScreenName for the Jabber-ID's in your contact list. Makes it much easier to keep track of who is who ...

**Comment by Echolon** [comment] 2019-01-09 21:12
Absolutely essential!

**Comment by anurodhp** [comment] 2019-01-18 02:20
yeah I'm going to do this. the inconstant names are killing me and I agree its ugly

**Comment by dholl** [comment] 2019-01-20 22:48
Is this a duplicate of #43 ?

**Comment by Echolon** [comment] 2020-01-04 22:43
Yep, I will close this because of #43

**Closed by Echolon** 2020-01-04 22:43 UTC
Labels: Feature, UI
