### ISSUE TITLE
XEP-0363 with openfire,HttpUploadComponent and jitsi

### ISSUE THREAD

**Issue by ageekhere** [anurodhp/Monal#30] opened 2016-03-22 22:07 UTC
Hey, has anyone got file http upload working for openfire?
I have setup HttpUploadComponent with openfire and have it connected as a Component Sessions. So in monal when I click to send image to another monal account it detects XEP-0363 support and tries to send the photo, however it times out with a timeout error.

Trying to workout what program has the issue (openfire, HttpUploadComponent ,monal).

Also has anyone got http upload working for jitsi? when I try pc to monal I get a can't send file error, not sure if jitsi supports XEP-0363 as I can't find any info on it.

**Comment by anurodhp** [comment] 2016-03-23 00:38
Are you using https with a valid cert? If not it won't work. Self signed cents won't work and http will never work. Apple does not allow insecure connections. 

If you need a free valid https cert get one from let's encrypt.

**Comment by ageekhere** [comment] 2016-03-23 01:29
I am using https but i did not create a cert yet, will try it now.

**Comment by ageekhere** [comment] 2016-05-22 08:49
still having issues with this, when I try and send a file from monal im to another monal account i get cannot connect to server, i see the send request in HttpUploadComponent but no error.

Has anyone got XEP-0363 working?

**Comment by aroquen** [comment] 2016-05-22 20:59
It works fine with prosody and mod_http_upload

**Comment by weiss** [comment] 2016-11-21 14:55
*Might* be a duplicate of #38.

**Comment by anurodhp** [comment] 2019-03-21 00:11
fixed an issue with content type passing that may address this

**Closed by anurodhp** 2019-03-21 00:11 UTC
