### ISSUE TITLE
Catalyst: Syncing of favorite MUCs

### ISSUE THREAD

**Issue by ingoj** [anurodhp/Monal#310] opened 2019-12-21 15:13 UTC
When adding a new MUC to the favorite list of MUCs and maybe set it to autojoin, there is no sync to the iOS version of Monal, so the Group Chat list there will be empty if not added manually. 
I would expect, when XMPP Compliance Test shows 100% that this kind of bookmarks will be synced, but maybe wrong in that as well. There might be good reasons as well to not sync the MUCs between the clients, but I guess most people nowadays would assume that they can add a Group Chat on either client that this will popup on other clients as well, the same way as contacts are "synced" between clients.

**Comment by foss-** [comment] 2020-01-27 10:04
This is a dupe of https://github.com/anurodhp/Monal/issues/19 right? @Echolon

**Comment by Echolon** [comment] 2020-01-27 10:21
I would say yes its a dupe actually, @anurodhp do you agree?

**Comment by anurodhp** [comment] 2020-01-27 11:45
Yeah

**Comment by Echolon** [comment] 2020-01-27 12:30
@ingoj 
Then I will close this in favor of #19 
Please refer to this issue with further comments. Thank you anyway for your report!

**Closed by Echolon** 2020-01-27 12:30 UTC
Labels: Catalyst, MUC
