### ISSUE TITLE
format send pictures so it get shown by clients with particular developers who dont want to show just any image ...

### ISSUE THREAD

**Issue by nanderer** [anurodhp/Monal#294] opened 2019-11-18 16:00 UTC
Hi there, sry for the edit, my android tuch screen is to sensitiv. I dont understand what imputmic is wanting but he indecates that there is an incorrect formating or so in images send from monal, i dont like this particular behavior to any rfc on the character and dont implement like you would do with Industrie Standard even reading between the line and test your stuff with all implementations you can get your hands on so that your thing works as good as possible with as much as possible...

Here you have the issue on conversations maybe you are able to understand what he is talking about, i dont... I just think he wants to get rich with conversations.im

Thanks a lot in advance!

> Have a look here: https://github.com/siacs/Conversations/issues/2641#issuecomment-332457050

**Comment by tmolitor-stud-tu** [comment] 2019-11-21 06:15
Thats a duplicate of my issue here: #224

To make the thread of arguments more clear, here is the start of the discussion which ends in the message you linked: https://github.com/siacs/Conversations/issues/3583

**Comment by tmolitor-stud-tu** [comment] 2019-11-21 06:18
Well, not exactly a duplicate, but strongly related.

**Comment by Echolon** [comment] 2020-01-04 21:53
I will close this because there are already two issues reported and the statement here is quite unclear formulated.

**Closed** 2020-01-04 22:01 UTC
Labels: Feature
