### ISSUE TITLE
Messages loss and no "new message" notification

### ISSUE THREAD

**Issue by Alexmark1** [anurodhp/Monal#373] opened 2020-03-12 07:40 UTC
Hi,
Yesterday I had an issue with lost messages again. Three messages sent by Monal 4.2.3 on an iOS 13 device were not received by Monal 4.2.3 on an iOS 12 device. Both were online simultaneously. There was no notification either. The three messages were sent over a time period of more than 30 minutes and they were the only messages between the two devices on that day (in other word: the whole communication did fail). This morning when I opened Gajim for the receiving account I saw all three. I know there is one update for Monal but I have been keeping it back to wait for the 12 byte IV issue to settle on all platforms. Not sure how to troubleshoot this; just wanted to bring it up that the issue of lost messages is apparently still there.
Thanks

**Comment by licaon-kter** [comment] 2020-03-12 07:54
Latest version, supported, is 4.4, do update and retry.

**Comment by Echolon** [comment] 2020-03-12 09:10
@Alexmark1 Thank yoi for you feedback!

Yes, would be very good if you first update the app please. Then feel free to comeback!

**Comment by licaon-kter** [comment] 2020-03-12 09:30
The problem is that 4.3 and 4.4 fix a lot of stuff, so try to update your other clients/contacts (for IV) then Monal.

**Comment by Alexmark1** [comment] 2020-03-12 10:18
Will do, but it will take some time (also to re-test; 4.2.3 seemed to work too at first, i.e. such problems seem to appear randomly).

Thanks for the advice and the great work you're doing!

**Comment by Alexmark1** [comment] 2020-03-13 07:54
I updated Monal to 4.4. Now had a case where 2 msgs were not received in a group chat by a user on Monal 4.4 on iOS 13. There was apparently a notification, but msgs were missing. Should I open a separate issue for this?

**Comment by Echolon** [comment] 2020-03-13 08:19
@Alexmark1 Hi, I suggest the following:

- I close this issue, as the problem seems to be gone
- You try to specificly through the open issues, if there is an existing one where you can add your comment. Also check the pinned "Overview" issue.
- If not please open a new issue!

That would be great thank you!

**Comment by Echolon** [comment] 2020-03-13 08:22
@Alexmark1 

This one: #223 or #296 ?

**Comment by Alexmark1** [comment] 2020-03-13 08:56
#296 maybe; if it means messages are lost in MUC, description is a bit sketchy. "Problem seems to be gone" is a little over-optimistic, though. We shall see.

**Comment by Echolon** [comment] 2020-03-13 09:05
I can reopen anytime. Once you are confindent about it, just open a new issue

13 mar. 2020 9:56:20 AM Alexmark1 <notifications@github.com>:

**Comment by Alexmark1** [comment] 2020-03-14 08:44
Yes, please re-open. Yesterday we had a lost message between two instances of Monal 4.4 on iOS (that makes it 1 out of 5). It was not the first message between the two devices and also not the first after the update to 4.4. The message is there in the backlog on my other devices, so it was correctly sent but not synced by Monal on the receiver side.

**Comment by Echolon** [comment] 2020-03-14 09:49
By notification you mean that Monal is telling you that a message wasn`t send?

**Comment by Alexmark1** [comment] 2020-03-14 11:01
Neither a "new message" notification for the receiver nor a "red dot" on the Monal icon nor a "delivery failed" for the sender

**Comment by tmolitor-stud-tu** [comment] 2020-04-16 12:30
could be related to the certificate expiration on ios13push.monal.im

**Comment by anurodhp** [comment] 2020-04-17 00:38
certs weren't expiring for 9 more days. Certs expire i july now

**Comment by tom709** [comment] 2020-04-24 09:21
I am again in a similar situation where my speaking partner (who runs Monal 4.6) is online and even actively opened the app but I cannot send messages to him from Gajim. We are both on the same XMPP server which is working. I tried sending several times and always got "‎error while sending message ( recipient-unavailable )".

**Comment by Echolon** [comment] 2020-08-19 15:20
Dear discussion participants,

I post this here because the next Monal update is upcoming. We [introduced many changes](https://github.com/anurodhp/Monal/pulse/monthly) to the back-end and we want to ensure usability and quality. Therefore we call for testers of the also upcoming beta on [Testflight](https://testflight.apple.com/join/RjIlyvqa). So, even we cannot guarantee all issues has been fixed or considered yet we ask for your help!

- [Monal blog](https://monal.im/blog/monal-4-8-coming-with-improved-notifications-and-translations/)
- [Support Monal](https://github.com/anurodhp/Monal/issues/363)
- [Translations on Weblate](https://hosted.weblate.org/engage/monal/)
- Public group chat: monal@chat.yax.im

We really appreciate your help and are looking forward to a better establishment of XMPP on iOS and Mac!

**Comment by Echolon** [comment] 2020-08-24 19:33
@Alexmark1 can you reproduce in the current beta?

**Comment by tmolitor-stud-tu** [comment] 2020-10-01 02:21
Should be fixed in the upcoming Monal 4.7 and in part even in Monal 4.7

**Closed by tmolitor-stud-tu** 2020-10-01 02:21 UTC
Labels: :iphone: iOS, :no_entry_sign:  Bug / Stability, :zap: Push notifications
