### ISSUE TITLE
Rename a contact in the MacOS desktop version

### ISSUE THREAD

**Issue by tv21** [anurodhp/Monal#292] opened 2019-11-11 00:20 UTC
I would very much like to be able to put names to contacts that differ from what is received from the server.  Would it be possible to please add that?

**Comment by anurodhp** [comment] 2019-11-11 02:20
In the contact info (I) button set a nick name 

--
Anurodh Pokharel

**Comment by tv21** [comment] 2019-11-11 20:16
If you mean the button that is an i within a circle at the top of the screen I see nothing about setting a nick name.  There is an "Encryption Keys" button and a "Resources" button and neither give you any way to set a nick name.  This is on the MacOS desktop Version 2.4.1 (149) which is the current version in the Mac App Store, are you talking about something available in a different version perhaps?

**Comment by anurodhp** [comment] 2019-11-25 04:37
Ah desktop, thanks you are right i forgot to add this. will fix.

**Comment by foss-** [comment] 2019-11-25 14:32
This is a dupe of https://github.com/anurodhp/Monal/issues/43

**Comment by Echolon** [comment] 2020-01-04 21:56
@anurodhp With respect to #43 can this be closed? Or do you haven't managed to implement to MacOS.

If so, I will restate the title for your.

**Comment by anurodhp** [comment] 2020-02-08 18:12
fixed in the catalyst version.

**Closed by anurodhp** 2020-02-08 18:12 UTC
Labels: Catalyst, Feature

**Comment by foss-** [comment] 2020-02-09 07:43
Version 4.3 (525) verified, thanks.
