### ISSUE TITLE
XEP-0184: Message Delivery Receipts - ACK only sent to the message sender

### ISSUE THREAD

**Issue by marmistrz** [anurodhp/Monal#339] opened 2020-01-08 19:37 UTC
I'm using two clients: Conversations & gajim. My contact is using Monal. When I send him a message, I only get the ACK on the device I sent it from, i.e.
* if I send a message from gajim, then only gajim shows the ACK, Conversations doesn't
* if I send a message from Conversations, then only Conversations shows the ACK, gajim doesn't

This looks like the ACK were sent to the full JID, whereas the bare JID should probably be preferred in this case - but this hypothesis may be wrong.

Edit by maintainer: 
XEP-0184: Message Delivery Receipts
https://xmpp.org/extensions/xep-0184.html

**Comment by anurodhp** [comment] 2020-01-08 19:49
ill check the xep and look at the code to see what it is doing. probably won't be fixed in 4.2.2 but will  be in 4.3 in feb .

**Comment by Alexmark1** [comment] 2020-01-27 08:10
I never got any delivery receipt when the receiver was using Monal (sender was either Gajim or Conversations). Do I need to enable sending of delivery receipts in Monal somehow?

**Comment by anurodhp** [comment] 2020-01-27 14:04
It should work automatically 

--
Anurodh Pokharel

**Comment by foss-** [comment] 2020-01-27 14:21
Delivery receipt seems to work in a Test Monal to Monal. Or at least I do see "Delivered" info for new sent messages when sent from Monal Catalyst latest beta.

**Comment by Alexmark1** [comment] 2020-02-04 09:24
Confirmed, delivery receipt works Monal-Monal, but not Gajim->Monal (while it does work Gajim->Conversations). What makes this more problematic is the fact that when the receiver does not open Monal quickly after receiving the notification, the sender will get en error; and then, even if the receiver opens Monal later and sees the message, the sender will still believe the message was lost.

**Comment by anurodhp** [comment] 2020-02-26 01:10
I think this is a problem with gajim. Ive seen this error too and sometimes hava gajim users send me multiple messages. The problem is that gajim likely thinks the "error" user unavailable means the message didn't arrive. This is part of the 90s legacy where when a user was offline they didn't get the message. With push there is a notification that goes to the user and they do eventually see it.

**Closed** 2020-02-26 01:10 UTC
Labels: Bug / Stability, XEP

**Comment by tmolitor-stud-tu** [comment] 2020-03-01 22:44
The receipts from prosody were not stored in the mam archive because the type of the message stanza was not set at all (should be "chat").
Maybe this is the reason for this bug.
(I fixed this a few hours ago, pull request is on its way)

**Comment by marmistrz** [comment] 2020-03-06 09:35
Why would then Conversations miss the ACKs when the messages are sent from gajim?

**Comment by tmolitor-stud-tu** [comment] 2020-04-16 10:48
@marmistrz you are right, in the code I can see that the receipt is sent to the full jid, not the bare one. usually this should be "fixed" by carbons, maybe you have carbons turned off somehow?

Monal 4.6 will have a fix for that.

The other thing you mentioned (errors) has some other reason, I described here: https://github.com/anurodhp/Monal/issues/352#issuecomment-614393801

@anurodhp 
> I think this is a problem with gajim. Ive seen this error too and sometimes hava gajim users send me multiple messages. The problem is that gajim likely thinks the "error" user unavailable means the message didn't arrive. This is part of the 90s legacy where when a user was offline they didn't get the message. With push there is a notification that goes to the user and they do eventually see it.

--> no, the reason is this: https://github.com/anurodhp/Monal/issues/352#issuecomment-614393801
