### ISSUE TITLE
Message was not encrypted for this device

### ISSUE THREAD

**Issue by bunnyfu** [anurodhp/Monal#240] opened 2019-05-02 19:42 UTC
Current testing scenario:
2 users, each logged into ejabberd server from macos (monal) and android (conversations). OMEMO enabled on all devices.

Correctly working when sending messages from conversations on android. Encrypted messages are received and correctly decrypted on android and macos.

Incorrectly working when sending messages from monal on macos. Encrypted messages are received and decrypted only on android. The receiving macos client displays error "Message was not encrypted for this device". 

It would seems that monal is not using all omemo keys when encrypting the messages. Hopefully this can be fixed?

**Comment by Echolon** [comment] 2019-05-02 20:25
Evtl. related: MUC: Encryption & device publishing #225

**Comment by anurodhp** [comment] 2019-05-29 23:46
could you test on the current beta (3.7) and see if it persists?

**Comment by lgnap** [comment] 2019-06-04 16:32
Hello, I had the same issue and so I'm seeking for the current beta.

Where can I find it? I searched the website, the brew install (same 2.4 - 135), and releases seems give source code only.

Thanks

**Comment by anurodhp** [comment] 2019-06-04 16:47
The brew version is a little old but you can just get it from the download link on the side bar at monal.im

**Comment by lgnap** [comment] 2019-06-04 16:53
This version is the 2.4. I tested it twice. We talk about the link `Download Latest OS X Beta` that provide monal.im/Monal-OSX/Monal-OSX.zip link ?

**Comment by tigexplorer** [comment] 2019-08-08 18:22
Hi, same problem here!
I don't use iOS or MacOS for myself but was trying to install Monal on a iPhone and a iPad of friends of mine.

But get always this messages if trying to set encryption for the contact.
The contact uses several OMEMO Devices, Conversations, Gajim and Dino!
Monal version, installed from App-Store on Juli/Aug 19 seems to be: 3.8 (377)

![Encryption_not_supportetd](https://user-images.githubusercontent.com/43775552/62727345-977cd480-ba19-11e9-8f3e-69afe3df4cf0.png)

**Comment by anurodhp** [comment] 2019-08-08 23:47
I have observed this too.  There is one case where i definitely see it on some servers if you are not subscribed to their other person's presence, then it can't get the OEMEO keys.  That isn't an issue that i can solve. I am looking at resolving the key fetching though.

**Comment by tigexplorer** [comment] 2019-08-09 07:45
> I have observed this too. There is one case where i definitely see it on some servers if you are not subscribed to their other person's presence, then it can't get the OEMEO keys. That isn't an issue that i can solve. I am looking at resolving the key fetching though.

Can yo describe what the monal user or the other user (me) have to do?
For myself, I use mainly Conversations for years. I don't remember that I have to set a "presence" that other users OMEMO clients send me an encrypted message.
 
I don't have any Apple device, so it's hard to tell my friends what to do?

After opening this issue here, I have start a new here. IMHO it's better as separate issue:
https://github.com/anurodhp/Monal/issues/272

**Comment by a11fruitless** [comment] 2019-08-13 04:42
Monal: 3.8.2 (iOS)

I can confirm this one as well. After recently reinstalling the app, I am now seeing the error posted above by tigexplorer. All users are subscribed to each other's presence. Neither my Gajim nor Converstaions client can see Monal's keys and vice versa.

I'm using an up-to-date Prosody 11.2 if that is any help here, and I can provide more detail about the server configuration if needed.

Funily enough, despite telling me that other client's dont support encryption, it also tells me it received encrypted messages from them it can't read. :)

**Comment by tigexplorer** [comment] 2019-08-13 16:17
Please don't misunderstood this mention: After failing OMEMO Chat with Monal, I've installed ChatSecure on both partner devices (iPhone/ iPad) and was trying it with the same contacts and the same client on the other side (Conversations), and it works.
But the UI of Monal, I think, is cleaner, so I was trying it at first. I think, it hasn't to do with the xmpp server? I used for all testing accounts wiuwiu.de, that is IMHO a Prosody.

**Comment by Echolon** [comment] 2020-02-19 19:09
@bunnyfu @lgnap @tigexplorer 

Hello guys, would you be so kind and test with the current version again and try to report the behavior?

**Comment by lgnap** [comment] 2020-02-19 20:37
Another issue not linked after `brew cask upgrade`, maybe should open another ticket for it ? 

<img width="424" alt="Screenshot 2020-02-19 at 21 35 56" src="https://user-images.githubusercontent.com/915876/74873698-fbd10700-535f-11ea-9dcc-cfb37367eee1.png">

**Comment by licaon-kter** [comment] 2020-02-19 20:50
Can't be checked sounds like an Apple issue, not a Monal one.

They changed this in Catalina. That message is dumb, do a Right click - open or put on Desktop, hold CTRL then click.

@anurodhp https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

**Comment by anurodhp** [comment] 2020-02-20 11:44
The catalyst builds are notarized. Will make them the version that is installed with brew

**Comment by tigexplorer** [comment] 2020-02-20 15:33
I got this from a blind friend.
He cannot deal with it, nor can he read the error message, maybe it is not properly defined for voiceover.
![GCM_Error](https://user-images.githubusercontent.com/43775552/74949919-ae57a700-53fe-11ea-9cc5-96ef2b36f2fe.jpg)

**Comment by Echolon** [comment] 2020-02-20 15:54
@tigexplorer you both use Monal?

**Comment by anurodhp** [comment] 2020-02-20 16:11
ill test the text in voiceover. It should read just like any other message.

**Comment by tigexplorer** [comment] 2020-02-21 08:28
> @tigexplorer you both use Monal?

No, Conversations on the other side.

**Comment by Echolon** [comment] 2020-02-21 08:36
@tigexplorer I think Conversations is going to update again to send correct inital vectors as well I think.

@iNPUTmice am I correct?

**Comment by licaon-kter** [comment] 2020-02-21 08:43
@Echolon 2.7.0 already has that, if from Play store

For F-Droid there's no ETA, but next cycle will build it, hopefully.

**Comment by Echolon** [comment] 2020-02-21 08:44
Thank you, then just look out for the Conversations update please @tigexplorer

**Comment by Echolon** [comment] 2020-08-19 15:16
Dear discussion participants,

I post this here because the next update is upcoming. We [introduced many changes](https://github.com/anurodhp/Monal/pulse/monthly) to the back-end and we want to ensure usability and quality. Therefore we call for testers of the also upcoming beta on [Testflight](https://testflight.apple.com/join/RjIlyvqa). So, even we cannot guarantee this issue has been fixed yet we ask for your help!

- [Monal blog](https://monal.im/blog/monal-4-8-coming-with-improved-notifications-and-translations/)
- [Support Monal](https://github.com/anurodhp/Monal/issues/363)
- [Translations on Weblate](https://hosted.weblate.org/engage/monal/)
- Public group chat: monal@chat.yax.im

We really appreciate your help and are looking forward to a better establishment of XMPP on iOS and Mac!

**Closed** 2020-11-08 18:24 UTC
Labels: :fire:  Priority, :fish: OMEMO, :no_entry_sign:  Bug / Stability
