### ISSUE TITLE
Availability Monal for French country

### ISSUE THREAD

**Issue by electro575** [anurodhp/Monal#280] opened 2019-09-09 12:40 UTC
Hi Anurodhp,

I have send you a request to have your app in French repo Ios.

Is it possible ? What's news ?

Thanks you a lot.

Good afternoon

**Comment by ldesgrange** [comment] 2019-11-13 22:05
I guess it's the same issue that ChatSecure had: https://github.com/ChatSecure/ChatSecure-iOS/issues/127
Apple requires a proof that the software has been declared to the French authority (France requiring that software doing encryption should be declared).
Maybe Monal people should get in touch with ChatSecure people to know about the process how to do that.

**Comment by anurodhp** [comment] 2019-12-13 04:28
in a nutshell, to make the french government happy i need to change the way encryption is done or register with them (seems to take years).  I am planning on changing the encryption for ios13 devices to use a native encryption feature in iOS 13 to get around gov regulations there.   Once i have that implemented i will release in france again

**Comment by anurodhp** [comment] 2019-12-13 04:33
dupe of #236

**Closed by anurodhp** 2019-12-13 04:33 UTC
